name: Build Test

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        product: [ { name: "App", value: app } ]
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      product: ${{ matrix.product.value }}
      outputs_dir: "${{ github.workspace }}/app/build/outputs"
      ver_name: ""

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Init Signature
        run: |
          keytool -genkeypair -v -keystore $GITHUB_WORKSPACE/app/key.jks \
            -alias ttsserver -keyalg RSA -keysize 2048 -validity 3650 \
            -storepass ttsserver123 -keypass ttsserver123 \
            -dname "CN=TTS Server CI, OU=CI, O=CI, L=CI, S=CI, C=PL"
          touch local.properties
          echo ALIAS_NAME='ttsserver' >> local.properties
          echo ALIAS_PASSWORD='ttsserver123' >> local.properties
          echo KEY_PASSWORD='ttsserver123' >> local.properties
          echo KEY_PATH='./key.jks' >> local.properties

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew assemble${{ env.product }}release --build-cache --parallel --daemon --warning-mode all

      - name: Set Version Name
        run: |
          echo "ver_name=$(grep -m 1 'versionName' ${{ env.outputs_dir }}/apk/${{ env.product }}/release/output-metadata.json | cut -d\" -f4)" >> $GITHUB_ENV

      - name: Upload APK To Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "TTS-Server_${{ env.product }}_${{ env.ver_name }}"
          path: ${{env.outputs_dir}}/apk/${{ env.product }}/release/*${{ env.ver_name }}.apk
